"""Three exact public source/model fixtures and material fail-closed checks.

Observation ccdbf3e45098076118bf9362b60d31b7a80dc1aab1dcc2e226a4aee58c92b596.
Producer 2d90a466a8ca3954494f82041409b39242c5c1f5. Lovdata / NLOD 2.0.
Fixtures are retained bytes/models, not generated by a producer imported in tests.
"""
from copy import deepcopy
import unittest
from law_history.structure import (VERSION, digest, first_difference, qualify,
                                   reverse_canonical_html)

FIXTURES = {'lov/1845-06-07': {'raw': '<!DOCTYPE html><html lang="nb"><head><title>Lov om Perlefiskeriet</title><base '
                           'href="https://lovdata.no/" /></head><body><header class="documentHeader" '
                           'id="hode"><dl class="data-document-key-info"><dt '
                           'class="legacyID">Datokode</dt><dd class="legacyID">LOV-1845-06-07</dd><dt '
                           'class="dokid">DokumentID</dt><dd class="dokid">NL/lov/1845-06-07</dd><dt '
                           'class="ministry">Departement</dt><dd class="ministry"><ul><li>Klima- og '
                           'miljødepartementet</li></ul></dd><dt class="legalArea">Rettsområde</dt><dd '
                           'class="legalArea"><ul><li><a href="legal-areas/09" title="Fiskeri- og fangstrett '
                           'og havbruk">Fiskeri- og fangstrett og havbruk</a> &gt; <a '
                           'href="legal-areas/09.03" title="Fiskeri">Fiskeri</a></li></ul></dd><dt '
                           'class="titleShort">Korttittel</dt><dd class="titleShort">Lov om '
                           'Perlefiskeriet</dd><dt class="title">Tittel</dt><dd class="title">Lov om '
                           'Perlefiskeriet</dd><dt class="refid">RefID</dt><dd '
                           'class="refid">lov/1845-06-07</dd><dt class="table-of-contents">Innhold</dt><dd '
                           'class="table-of-contents"><ul class="tocTopUl"><li><a href="#dokument">Lov om '
                           'Perlefiskeriet</a></li></ul></dd></dl></header><main class="documentBody" '
                           'data-lovdata-URL="NL/lov/1845-06-07" id="dokument"><h1>Lov om '
                           'Perlefiskeriet</h1><article class="legalP" id="ledd-1">Forordningen af 28de Mai '
                           '1718 om Perlefangsten i Christianssands og andre Stifter i Norge samt den '
                           'Kongelige Resolution af 5te Januar 1791 om Perlefiskeriet i førstmeldte Stift '
                           'tilligemed alle øvrige særskilt om dette Fiskeri udgivne Bestemmelser ophæves '
                           'herved, saaledes at Perlefiskeriet fremtidigen skal tilkomme Eierne af de '
                           'Grunde, paa hvilke Muslingerne findes.</article></main></body></html>',
                    'model': {'refid': 'lov/1845-06-07',
                              'title': 'Lov om Perlefiskeriet',
                              'short_title': 'Lov om Perlefiskeriet',
                              'ministry': 'Klima- og miljødepartementet',
                              'date_in_force': '',
                              'last_amended': '',
                              'last_amended_in_force': '',
                              'legal_area': 'Fiskeri- og fangstrett og havbruk>Fiskeri',
                              'sections': [],
                              'top_level_articles': [],
                              'top_level_paragraphs': [{'text': 'Forordningen af 28de Mai 1718 om '
                                                                'Perlefangsten i Christianssands og andre '
                                                                'Stifter i Norge samt den Kongelige '
                                                                'Resolution af 5te Januar 1791 om '
                                                                'Perlefiskeriet i førstmeldte Stift '
                                                                'tilligemed alle øvrige særskilt om dette '
                                                                'Fiskeri udgivne Bestemmelser ophæves '
                                                                'herved, saaledes at Perlefiskeriet '
                                                                'fremtidigen skal tilkomme Eierne af de '
                                                                'Grunde, paa hvilke Muslingerne findes.',
                                                        'list_items': [],
                                                        'list_style': '',
                                                        'trailing_text': '',
                                                        'ordered_blocks': []}],
                              'remainders': []},
                    'raw_sha256': '9107f86d07f0c8430334fa0340cc6a75f2ad714c30b7b5c37d275858816f3b76',
                    'occurrence_id': '97422e60d929fd2400ec5c613b7bc8e7fd641dda61b62a6649412fbaef4c200d'},
 'lov/1949-07-28-15': {'raw': '<!DOCTYPE html><html lang="nb"><head><title>Lov om adgang for Kongen til å '
                              'inngå overenskomster med fremmede stater til forebyggelse av '
                              'dobbeltbeskatning mv. (dobbeltbeskatningsavtaleloven)</title><base '
                              'href="https://lovdata.no/" /></head><body><header class="documentHeader" '
                              'id="hode"><dl class="data-document-key-info"><dt '
                              'class="legacyID">Datokode</dt><dd class="legacyID">LOV-1949-07-28-15</dd><dt '
                              'class="dokid">DokumentID</dt><dd class="dokid">NL/lov/1949-07-28-15</dd><dt '
                              'class="ministry">Departement</dt><dd '
                              'class="ministry"><ul><li>Finansdepartementet</li></ul></dd><dt '
                              'class="dateInForce">I kraft fra</dt><dd '
                              'class="dateInForce">1949-07-28</dd><dt '
                              'class="lastChangeInForce">Ikrafttredelse av siste endring</dt><dd '
                              'class="lastChangeInForce">2016-06-17</dd><dt class="lastChangedBy">Sist '
                              'endret ved</dt><dd class="lastChangedBy"><a '
                              'href="lov/2016-06-17-33">lov/2016-06-17-33</a></dd><dt '
                              'class="legalArea">Rettsområde</dt><dd class="legalArea"><ul><li><a '
                              'href="legal-areas/27" title="Skatte- og avgiftsrett">Skatte- og '
                              'avgiftsrett</a> &gt; <a href="legal-areas/27.08" '
                              'title="Skatteavtaler">Skatteavtaler</a></li></ul></dd><dt '
                              'class="lastupdated">Siste rettelse</dt><dd class="lastupdated">2021-09-28 '
                              '(faglige fotnoter fjernet, struktur, UU-tilpasset)</dd><dt '
                              'class="titleShort">Korttittel</dt><dd '
                              'class="titleShort">Dobbeltbeskatningsavtaleloven</dd><dt '
                              'class="title">Tittel</dt><dd class="title">Lov om adgang for Kongen til å '
                              'inngå overenskomster med fremmede stater til forebyggelse av '
                              'dobbeltbeskatning mv. (dobbeltbeskatningsavtaleloven)</dd><dt '
                              'class="miscInformation">Annet om dokumentet</dt><dd '
                              'class="miscInformation">Jf. <i>tidligere</i> lover 8 apr 1905 nr. 2 § 1 (3), '
                              '<a href="lov/1911-08-18-8/§35">18 aug 1911 nr. 8 § 35</a> (2), 18 aug 1911 '
                              'nr. 9 § 29 (2). <a href="lov/2016-06-17-33">Lovens tittel endret ved lov 17 '
                              'juni 2016 nr. 33</a>.</dd><dt class="refid">RefID</dt><dd '
                              'class="refid">lov/1949-07-28-15</dd><dt '
                              'class="table-of-contents">Innhold</dt><dd class="table-of-contents"><ul '
                              'class="tocTopUl"><li><a href="#dokument">Lov om adgang for Kongen til å inngå '
                              'overenskomster med fremmede stater til forebyggelse av dobbeltbeskatning mv. '
                              '(dobbeltbeskatningsavtaleloven)</a><ul class="tocSubUl"><li><a '
                              'href="#paragraf-1">§ 1.</a></li><li><a href="#paragraf-2">§ 2.</a></li><li><a '
                              'href="#paragraf-3">§ 3.</a></li></ul></li></ul></dd></dl></header><main '
                              'class="documentBody" data-lovdata-URL="NL/lov/1949-07-28-15" '
                              'id="dokument"><h1>Lov om adgang for Kongen til å inngå overenskomster med '
                              'fremmede stater til forebyggelse av dobbeltbeskatning mv. '
                              '(dobbeltbeskatningsavtaleloven)</h1><article class="legalArticle" '
                              'data-lovdata-URL="NL/lov/1949-07-28-15/§1" data-name="§1" id="paragraf-1"><h2 '
                              'class="legalArticleHeader"><span class="legalArticleValue">§ '
                              '1</span>.</h2><article class="legalP" id="paragraf-1-ledd-1">Under forbehold '
                              'av gjensidighet kan Kongen med Stortingets samtykke ved overenskomst med '
                              'fremmed stats regjering<ol class="defaultList" type="1"><li data-name="1." '
                              'value="1"><article class="listArticle" '
                              'id="paragraf-1-ledd-1-punkt-1"><article class="legalP" '
                              'id="paragraf-1-ledd-1-punkt-1-ledd-1">med omsyn til offentlige skatter og '
                              'avgifter fastsette regler for deling av skattefundamentene og herunder '
                              'innrømme slik lempning i beskatningen at dobbeltbeskatning helt eller delvis '
                              'unngås,</article></article></li><li data-name="2." value="2"><article '
                              'class="listArticle" id="paragraf-1-ledd-1-punkt-2"><article class="legalP" '
                              'id="paragraf-1-ledd-1-punkt-2-ledd-1">vedta bestemmelser om at norske '
                              'myndigheter, uten hinder av gjeldende bestemmelser om taushetsplikt, skal '
                              'innhente og meddele opplysninger til bruk for vedkommende stats myndigheter '
                              'ved utskrivningen av offentlige skatter og avgifter, '
                              'og</article></article></li><li data-name="3." value="3"><article '
                              'class="listArticle" id="paragraf-1-ledd-1-punkt-3"><article class="legalP" '
                              'id="paragraf-1-ledd-1-punkt-3-ledd-1">vedta bestemmelser om at eksigible krav '
                              'på offentlige skatter og avgifter, utskrevet i vedkommende stat, skal være '
                              'bindende her i riket, og kunne inndrives av den norske stat etter de regler '
                              'som gjelder for inndriving og oppkreving av tilsvarende eller lignende norske '
                              'skatter og '
                              'avgifter.</article></article></li></ol></article></article><article '
                              'class="legalArticle" data-lovdata-URL="NL/lov/1949-07-28-15/§2" '
                              'data-name="§2" id="paragraf-2"><h2 class="legalArticleHeader"><span '
                              'class="legalArticleValue">§ 2</span>.</h2><article class="legalP" '
                              'id="paragraf-2-ledd-1">Bestemmelser i den øvrige lovgivning om plikt til å gi '
                              'opplysninger til bruk for myndighetene ved utskriving av skatt eller avgift '
                              'for andre skatte- eller avgiftspliktige får tilsvarende anvendelse, når det '
                              'med hjemmel i overenskomst med fremmed stat søkes innhentet opplysninger til '
                              'bruk for utenlandske skattemyndigheter.</article></article><article '
                              'class="legalArticle" data-lovdata-URL="NL/lov/1949-07-28-15/§3" '
                              'data-name="§3" id="paragraf-3"><h2 class="legalArticleHeader"><span '
                              'class="legalArticleValue">§ 3</span>.</h2><article class="legalP" '
                              'id="paragraf-3-ledd-1">Denne lov trer i kraft straks. – – '
                              '–</article></article></main></body></html>',
                       'model': {'refid': 'lov/1949-07-28-15',
                                 'title': 'Lov om adgang for Kongen til å inngå overenskomster med fremmede '
                                          'stater til forebyggelse av dobbeltbeskatning mv. '
                                          '(dobbeltbeskatningsavtaleloven)',
                                 'short_title': 'Dobbeltbeskatningsavtaleloven',
                                 'ministry': 'Finansdepartementet',
                                 'date_in_force': '1949-07-28',
                                 'last_amended': 'lov/2016-06-17-33',
                                 'last_amended_in_force': '2016-06-17',
                                 'legal_area': 'Skatte- og avgiftsrett>Skatteavtaler',
                                 'sections': [],
                                 'top_level_articles': [{'name': '§1',
                                                         'header_text': '§ 1',
                                                         'paragraphs': [{'text': 'Under forbehold av '
                                                                                 'gjensidighet kan Kongen '
                                                                                 'med Stortingets samtykke '
                                                                                 'ved overenskomst med '
                                                                                 'fremmed stats regjering',
                                                                         'list_items': [{'marker': '1.',
                                                                                         'value': '1',
                                                                                         'paragraphs': [{'text': 'med '
                                                                                                                 'omsyn '
                                                                                                                 'til '
                                                                                                                 'offentlige '
                                                                                                                 'skatter '
                                                                                                                 'og '
                                                                                                                 'avgifter '
                                                                                                                 'fastsette '
                                                                                                                 'regler '
                                                                                                                 'for '
                                                                                                                 'deling '
                                                                                                                 'av '
                                                                                                                 'skattefundamentene '
                                                                                                                 'og '
                                                                                                                 'herunder '
                                                                                                                 'innrømme '
                                                                                                                 'slik '
                                                                                                                 'lempning '
                                                                                                                 'i '
                                                                                                                 'beskatningen '
                                                                                                                 'at '
                                                                                                                 'dobbeltbeskatning '
                                                                                                                 'helt '
                                                                                                                 'eller '
                                                                                                                 'delvis '
                                                                                                                 'unngås,',
                                                                                                         'list_items': [],
                                                                                                         'list_style': '',
                                                                                                         'trailing_text': '',
                                                                                                         'ordered_blocks': []}]},
                                                                                        {'marker': '2.',
                                                                                         'value': '2',
                                                                                         'paragraphs': [{'text': 'vedta '
                                                                                                                 'bestemmelser '
                                                                                                                 'om '
                                                                                                                 'at '
                                                                                                                 'norske '
                                                                                                                 'myndigheter, '
                                                                                                                 'uten '
                                                                                                                 'hinder '
                                                                                                                 'av '
                                                                                                                 'gjeldende '
                                                                                                                 'bestemmelser '
                                                                                                                 'om '
                                                                                                                 'taushetsplikt, '
                                                                                                                 'skal '
                                                                                                                 'innhente '
                                                                                                                 'og '
                                                                                                                 'meddele '
                                                                                                                 'opplysninger '
                                                                                                                 'til '
                                                                                                                 'bruk '
                                                                                                                 'for '
                                                                                                                 'vedkommende '
                                                                                                                 'stats '
                                                                                                                 'myndigheter '
                                                                                                                 'ved '
                                                                                                                 'utskrivningen '
                                                                                                                 'av '
                                                                                                                 'offentlige '
                                                                                                                 'skatter '
                                                                                                                 'og '
                                                                                                                 'avgifter, '
                                                                                                                 'og',
                                                                                                         'list_items': [],
                                                                                                         'list_style': '',
                                                                                                         'trailing_text': '',
                                                                                                         'ordered_blocks': []}]},
                                                                                        {'marker': '3.',
                                                                                         'value': '3',
                                                                                         'paragraphs': [{'text': 'vedta '
                                                                                                                 'bestemmelser '
                                                                                                                 'om '
                                                                                                                 'at '
                                                                                                                 'eksigible '
                                                                                                                 'krav '
                                                                                                                 'på '
                                                                                                                 'offentlige '
                                                                                                                 'skatter '
                                                                                                                 'og '
                                                                                                                 'avgifter, '
                                                                                                                 'utskrevet '
                                                                                                                 'i '
                                                                                                                 'vedkommende '
                                                                                                                 'stat, '
                                                                                                                 'skal '
                                                                                                                 'være '
                                                                                                                 'bindende '
                                                                                                                 'her '
                                                                                                                 'i '
                                                                                                                 'riket, '
                                                                                                                 'og '
                                                                                                                 'kunne '
                                                                                                                 'inndrives '
                                                                                                                 'av '
                                                                                                                 'den '
                                                                                                                 'norske '
                                                                                                                 'stat '
                                                                                                                 'etter '
                                                                                                                 'de '
                                                                                                                 'regler '
                                                                                                                 'som '
                                                                                                                 'gjelder '
                                                                                                                 'for '
                                                                                                                 'inndriving '
                                                                                                                 'og '
                                                                                                                 'oppkreving '
                                                                                                                 'av '
                                                                                                                 'tilsvarende '
                                                                                                                 'eller '
                                                                                                                 'lignende '
                                                                                                                 'norske '
                                                                                                                 'skatter '
                                                                                                                 'og '
                                                                                                                 'avgifter.',
                                                                                                         'list_items': [],
                                                                                                         'list_style': '',
                                                                                                         'trailing_text': '',
                                                                                                         'ordered_blocks': []}]}],
                                                                         'list_style': '1',
                                                                         'trailing_text': '',
                                                                         'ordered_blocks': []}],
                                                         'trailing_text': '',
                                                         'remainders': []},
                                                        {'name': '§2',
                                                         'header_text': '§ 2',
                                                         'paragraphs': [{'text': 'Bestemmelser i den øvrige '
                                                                                 'lovgivning om plikt til å '
                                                                                 'gi opplysninger til bruk '
                                                                                 'for myndighetene ved '
                                                                                 'utskriving av skatt eller '
                                                                                 'avgift for andre skatte- '
                                                                                 'eller avgiftspliktige får '
                                                                                 'tilsvarende anvendelse, '
                                                                                 'når det med hjemmel i '
                                                                                 'overenskomst med fremmed '
                                                                                 'stat søkes innhentet '
                                                                                 'opplysninger til bruk for '
                                                                                 'utenlandske '
                                                                                 'skattemyndigheter.',
                                                                         'list_items': [],
                                                                         'list_style': '',
                                                                         'trailing_text': '',
                                                                         'ordered_blocks': []}],
                                                         'trailing_text': '',
                                                         'remainders': []},
                                                        {'name': '§3',
                                                         'header_text': '§ 3',
                                                         'paragraphs': [{'text': 'Denne lov trer i kraft '
                                                                                 'straks. – – –',
                                                                         'list_items': [],
                                                                         'list_style': '',
                                                                         'trailing_text': '',
                                                                         'ordered_blocks': []}],
                                                         'trailing_text': '',
                                                         'remainders': []}],
                                 'top_level_paragraphs': [],
                                 'remainders': []},
                       'raw_sha256': '0b4c06febecf138ed76d08335aec5888e4b63701a08a7652594939101968ca89',
                       'occurrence_id': 'f14be30b59f6e4c25da59f92c82a1d3ccb20ecc2aacfa5d2f21e8e7d5b3f8474'},
 'forskrift/2022-09-02-1529': {'raw': '<!DOCTYPE html><html lang="no"><head><title>Delegering av Kongens '
                                      'myndighet etter finansavtaleloven</title><base '
                                      'href="https://lovdata.no/" /></head><body><header '
                                      'class="documentHeader" id="hode"><dl '
                                      'class="data-document-key-info"><dt class="legacyID">Datokode</dt><dd '
                                      'class="legacyID">FOR-2022-09-02-1529</dd><dt '
                                      'class="dokid">DokumentID</dt><dd '
                                      'class="dokid">DEL/forskrift/2022-09-02-1529</dd><dt '
                                      'class="ministry">Departement</dt><dd class="ministry"><ul><li>Justis- '
                                      'og beredskapsdepartementet</li></ul></dd><dt '
                                      'class="subunit">Etat</dt><dd '
                                      'class="subunit"><ul><li>Lovavdelingen</li></ul></dd><dt '
                                      'class="dateInForce">I kraft fra</dt><dd '
                                      'class="dateInForce">2022-09-02</dd><dt '
                                      'class="basedOn">Hjemmel</dt><dd class="basedOn"><ul><li><a '
                                      'href="lov/2020-12-18-146">lov/2020-12-18-146</a></li></ul></dd><dt '
                                      'class="dateOfPublication">Kunngjort</dt><dd '
                                      'class="dateOfPublication">2022-09-02 14:30</dd><dt '
                                      'class="title">Tittel</dt><dd class="title">Delegering av Kongens '
                                      'myndighet etter finansavtaleloven</dd><dt '
                                      'class="miscInformation">Annet om dokumentet</dt><dd '
                                      'class="miscInformation"><strong>Hjemmel:</strong> Fastsatt ved '
                                      'kgl.res. 2. september 2022 med hjemmel i <a '
                                      'href="lov/2020-12-18-146">lov 18. desember 2020 nr. 146 om '
                                      'finansavtaler (finansavtaleloven)</a>. Fremmet av Justis- og '
                                      'beredskapsdepartementet.</dd><dt class="refid">RefID</dt><dd '
                                      'class="refid">forskrift/2022-09-02-1529</dd><dt '
                                      'class="table-of-contents">Innhold</dt><dd '
                                      'class="table-of-contents"><ul class="tocTopUl"><li><a '
                                      'href="#dokument">Delegering av Kongens myndighet etter '
                                      'finansavtaleloven</a></li></ul></dd></dl></header><main '
                                      'class="documentBody" data-lovdata-URL="DEL/forskrift/2022-09-02-1529" '
                                      'id="dokument"><h1>Delegering av Kongens myndighet etter '
                                      'finansavtaleloven</h1><article class="legalP" id="ledd-1">Kongens '
                                      'myndighet etter loven delegeres til Justis- og '
                                      'beredskapsdepartementet.</article></main></body></html>',
                               'model': {'refid': 'forskrift/2022-09-02-1529',
                                         'title': 'Delegering av Kongens myndighet etter finansavtaleloven',
                                         'short_title': '',
                                         'ministry': 'Justis- og beredskapsdepartementet',
                                         'date_in_force': '2022-09-02',
                                         'last_amended': '',
                                         'last_amended_in_force': '',
                                         'legal_area': '',
                                         'sections': [],
                                         'top_level_articles': [],
                                         'top_level_paragraphs': [{'text': 'Kongens myndighet etter loven '
                                                                           'delegeres til Justis- og '
                                                                           'beredskapsdepartementet.',
                                                                   'list_items': [],
                                                                   'list_style': '',
                                                                   'trailing_text': '',
                                                                   'ordered_blocks': []}],
                                         'remainders': []},
                               'raw_sha256': '14930283a7383da487766be452a3deee74638822a4a1c4b446ef7d80d74a89e0',
                               'occurrence_id': '1b399897f57214a3f91cd37c6007fb7870af7dacce7f90b971da1d9ff69016ba'}}

class StructureTests(unittest.TestCase):
    def qualify_fixture(self, refid, model=None, raw=None):
        fixture = FIXTURES[refid]
        return qualify(raw if raw is not None else fixture["raw"].encode("utf-8"),
                       model if model is not None else fixture["model"], refid)

    def test_three_real_complete_bodies_match_all_traversals(self):
        for refid, fixture in FIXTURES.items():
            with self.subTest(refid=refid):
                raw = fixture["raw"].encode("utf-8")
                self.assertEqual(digest(raw), fixture["raw_sha256"])
                report, inventory, source, paths, modeled, output = self.qualify_fixture(refid)
                self.assertEqual(report["status"], "passed", report["reasons"])
                self.assertEqual(report["projection_contract"], "strict-document-body-v1")
                self.assertEqual(report["observation_canonical_status"], "not_verified")
                self.assertEqual(report["legal_valid_time_status"], "unresolved")
                self.assertEqual(source, modeled)
                self.assertEqual(source, reverse_canonical_html(output))
                self.assertEqual(len(source), len(paths))
                self.assertTrue(inventory)
                self.assertFalse(any(row["disposition"] in {"pending", "unclassified"} for row in inventory))
                self.assertIn(fixture["raw_sha256"], output)
                self.assertEqual(output, self.qualify_fixture(refid)[5])

    def test_real_list_reorder_and_article_omission_fail_without_output(self):
        refid = "lov/1949-07-28-15"
        changed = deepcopy(FIXTURES[refid]["model"])
        changed["top_level_articles"][0]["paragraphs"][0]["list_items"].reverse()
        omitted = deepcopy(FIXTURES[refid]["model"])
        omitted["top_level_articles"].pop()
        for candidate in (changed, omitted):
            report, *_, output = self.qualify_fixture(refid, model=candidate)
            self.assertEqual(report["status"], "failed")
            self.assertEqual(report["reasons"][0]["code"], "ordered_source_model_mismatch")
            self.assertIsNone(output)

    def test_changed_visible_output_marker_is_detected(self):
        _, _, source, _, _, output = self.qualify_fixture("lov/1949-07-28-15")
        changed = output.replace('class="marker">1.', 'class="marker">9.', 1)
        self.assertNotEqual(changed, output)
        self.assertIsNotNone(first_difference(source, reverse_canonical_html(changed)))

    def test_multiple_paragraphs_in_one_item_keep_separate_boundaries(self):
        raw = (b'<main class="documentBody"><h1>Paragraph boundary probe</h1>'
               b'<article class="legalP"><ol type="1"><li data-name="1." value="1">'
               b'<article class="listArticle"><article class="legalP">First paragraph.</article>'
               b'<article class="legalP">Second paragraph.</article></article>'
               b'</li></ol></article></main>')
        model = {"title": "Paragraph boundary probe", "top_level_paragraphs": [{
            "list_style": "1", "list_items": [{"marker": "1.", "value": "1", "paragraphs": [
                {"text": "First paragraph."}, {"text": "Second paragraph."}]}]}]}
        report, _, source, _, modeled, output = qualify(raw, model, "lov/paragraph-boundary-probe")
        self.assertEqual(report["status"], "passed", report["reasons"])
        self.assertEqual(source, modeled)
        self.assertEqual(source, reverse_canonical_html(output))
        first = source.index(["text", "First paragraph."])
        self.assertEqual(source[first:first + 4], [
            ["text", "First paragraph."], ["close", "paragraph"],
            ["open", "paragraph"], ["text", "Second paragraph."]])
        self.assertNotIn("li>.legal-paragraph{display:inline}", output)

    def test_unrepresented_paragraph_marker_and_title_attribute_fail_closed(self):
        refid = "lov/1845-06-07"
        raw = FIXTURES[refid]["raw"].replace('class="legalP"', 'class="legalP" data-name="1."', 1).encode("utf-8")
        report, *_, output = self.qualify_fixture(refid, raw=raw)
        self.assertEqual(report["status"], "failed")
        self.assertIn("unsupported_source_attribute", report["reason_counts"])
        self.assertIsNone(output)
        original = self.qualify_fixture(refid)[5]
        with self.assertRaises(ValueError):
            reverse_canonical_html(original.replace("<h1>", '<h1 hidden="hidden">', 1))


if __name__ == "__main__":
    unittest.main()
